# Generated by Django 5.2.16 on 2026-07-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='adjustment_direction',
            field=models.CharField(choices=[('add', 'Add Stock (+)'), ('remove', 'Remove Stock (-)')], default='remove', help_text='Add or remove stock during adjustment', max_length=10),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('correction', 'Correction')], help_text='Reason for stock adjustment (only for adjustment type)', max_length=20),
        ),
    ]
