# Generated by Django 5.2.16 on 2026-07-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
        ('stock', '0002_stocktransaction_adjustment_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Batch / lot number (e.g. LOT-2025-001)', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry / best-before date (leave blank if not applicable)', null=True)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current remaining stock in this batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Batch',
                'verbose_name_plural': 'Product Batches',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='stocktransactionitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this item was taken from / added to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='stock.productbatch'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['product', 'expiry_date'], name='stock_produ_product_22d6d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('product', 'batch_number')},
        ),
    ]
