# Generated by Django 5.2.16 on 2026-07-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stocktransaction_adjustment_direction_and_more'),
    ]

    operations = [
    ]
