# Generated by Django 5.2.16 on 2026-07-14 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Warehouse', max_length=255)),
                ('tax_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Tax ID / NPWP')),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('warehouse_name', models.CharField(default='Main Warehouse', max_length=255)),
                ('warehouse_location', models.CharField(blank=True, default='', max_length=255)),
                ('warehouse_code', models.CharField(blank=True, default='WH-01', max_length=20)),
                ('default_currency', models.CharField(default='IDR', max_length=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Global minimum stock notification threshold', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Low Stock Alert Threshold')),
                ('enable_low_stock_alert', models.BooleanField(default=True, verbose_name='Enable Low Stock Alerts')),
                ('enable_low_stock_email', models.BooleanField(default=False, help_text='Send email when stock is low', verbose_name='Email Alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
