# Generated by Django 5.2.16 on 2026-07-14 15:26

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit — unique product code', max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Barcode')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Purchase Price')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Selling Price')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Current Stock')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='Minimum Stock')),
                ('image', models.ImageField(blank=True, upload_to=products.models.product_image_path, verbose_name='Product Image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier', verbose_name='Supplier')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='units.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'sku', 'barcode'], name='products_pr_name_e9a22d_idx')],
            },
        ),
    ]
