# Generated by Django 5.2.16 on 2026-07-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit — unique product code', max_length=50, unique=True, verbose_name='SKU'),
        ),
    ]
